### PR TITLE
cmd: check for errors on log websockets

### LINKED ISSUE #526: Websocket segfaults when no internet connection
set up a remote, and *without running the inertia daemon*, try:

```
~/Projects/inertia-deploy-test some-branch*
❯ inertia local logs
[WARNING] Configuration version 'test' does not match your Inertia CLI version 'v0.5.0'
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1344902]

goroutine 1 [running]:
github.com/ubclaunchpad/inertia/vendor/github.com/gorilla/websocket.(*Conn).Close(0x0, 0x0, 0x1a016a0)
	/home/travis/gopath/src/github.com/ubclaunchpad/inertia/vendor/github.com/gorilla/websocket/conn.go:331 +0x22
panic(0x17f3760, 0x20ef250)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:513 +0x1b9
github.com/ubclaunchpad/inertia/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0x0, 0x0, 0xc00014baf0, 0x1028da2, 0xc0000ca490, 0xc00014bb10)
	/home/travis/gopath/src/github.com/ubclaunchpad/inertia/vendor/github.com/gorilla/websocket/conn.go:938 +0x26
github.com/ubclaunchpad/inertia/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0x0, 0x1a016b8, 0x0, 0x0, 0x1a016a0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ubclaunchpad/inertia/vendor/github.com/gorilla/websocket/conn.go:1028 +0x2f
github.com/ubclaunchpad/inertia/cmd/host.(*HostCmd).attachLogsCmd.func1(0xc0001c2c80, 0x211da98, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ubclaunchpad/inertia/cmd/host/host.go:306 +0x256
github.com/ubclaunchpad/inertia/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001c2c80, 0x211da98, 0x0, 0x0, 0xc0001c2c80, 0x211da98)
	/home/travis/gopath/src/github.com/ubclaunchpad/inertia/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/ubclaunchpad/inertia/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d1680, 0x2e, 0xc0000a7480, 0xc0000a7488)
	/home/travis/gopath/src/github.com/ubclaunchpad/inertia/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/ubclaunchpad/inertia/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000d1680, 0x6, 0xc0000a7480)
	/home/travis/gopath/src/github.com/ubclaunchpad/inertia/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/travis/gopath/src/github.com/ubclaunchpad/inertia/main.go:14 +0x4e
```

### PR DESCRIPTION
**Pull request by didil**
:tickets: **Ticket(s)**: Closes #526 

---

## :construction_worker: Changes

add error checking on client.LogsWebSocket + test

## :flashlight: Testing Instructions

make test

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -322,6 +322,9 @@ func (c *Client) LogsWebSocket(container string, entries int) (SocketReader, err
 	if err == websocket.ErrBadHandshake {
 		return nil, fmt.Errorf("websocket handshake failed with status %d", resp.StatusCode)
 	}
+	if err != nil {
+		return nil, err
```
Comment (bobheadxi) [inline client/client.go]: we could include more context here (although I know most of the codebase is a little older and doesn't do this, it's still generally good practice), ie:

```suggestion
		return nil, fmt.Errorf("failed to connect to daemon at %s: %s", url.Host, err.Error())
```

**Comment by bobheadxi** [comment]
@didil looks like Windows returns a different error when the websocket connection fails:
https://ci.appveyor.com/project/ubclaunchpad/inertia/builds/22186666

```
--- FAIL: TestLogsWebsocketNoDaemon (1.02s)
    client_test.go:378: 
        	Error Trace:	client_test.go:378
        	Error:      	"failed to connect to daemon at 127.0.0.1:1150: dial tcp 127.0.0.1:1150: connectex: No connection could be made because the target machine actively refused it." does not contain "connect: connection refused"
        	Test:       	TestLogsWebsocketNoDaemon
FAIL
coverage: 55.6% of statements
FAIL	github.com/ubclaunchpad/inertia/client	3.164s
```

unfortunately I can't seem to get Appveyor to trigger on our end for forked repositories, so a Windows test run was never made for this PR. Do you mind putting in a PR to address this?
