### PR TITLE
Fix config send, add --dest flag

### LINKED ISSUE #266: Add --dest flag for inertia [remote] send

### PR DESCRIPTION
**Pull request by bobheadxi**
:tickets: **Ticket(s)**: Closes #266

---

## :construction_worker: Changes

- Fix incorrect send destination
- Add `--dest` flag to specify where you want your file to go relative to project root

## :flashlight: Testing Instructions

n/a

### CODE REVIEW

File: deploy.go [hunk 1]
```diff
@@ -372,8 +373,15 @@ deployment. Provide a relative path to your file.`,
...
-		// Destination path
-		remotePath := path.Join(common.DaemonProjectPath, args[0])
+		// Get flag for destination
+		dest, err := cmd.Flags().GetString("dest")
+		if err != nil {
+			log.Fatal(err.Error())
+		}
+
+		// Destination path - todo: allow config
+		projectPath := "/app/host/inertia/project"
```
Comment (brian-nguyen) [inline deploy.go]: Quick question: Why does the path start with `/app/host`?

File: deploy.go [hunk 2]
```diff
@@ -84,6 +84,7 @@ Run 'inertia [REMOTE] init' to gather this information.`,
 		cmd.AddCommand(ssh)
 
 		send := deepCopy(cmdDeploymentSendFile)
+		send.Flags().StringP("dest", "d", "", "Path relative from project root to send file to")
```
Comment (brian-nguyen) [inline deploy.go]: 🔥

File: deploy.go (hunk 1 above)
Comment (bobheadxi) [reply deploy.go]: in `client/scripts/daemon-up.sh`, we mount the host home directory to there:

```bash
sudo docker run -d \
    --restart unless-stopped \
    -p "$DAEMON_PORT":"$CONTAINER_PORT" \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$HOME":/app/host \ # <--- relevant line
    -e HOME="$HOME" \
    -e SSH_KNOWN_HOSTS='/app/host/.ssh/known_hosts' \
    --name "$DAEMON_NAME" \
    "$IMAGE" "$HOST_ADDRESS" > /dev/null 2>&1
```

so on the host, `$HOME/inertia/project` would map to `/app/host/inertia/project`. Interestingly enough, we have to do some finnicking around that when we execute Docker commands - because the socket is on the host, we need to translate `/app/host/` paths back to `$HOME/` paths 😅 See https://github.com/ubclaunchpad/inertia/blob/v0.4.0-rc2/daemon/inertiad/project/build.go#L36

Comment (brian-nguyen) [reply deploy.go]: image
