### PR TITLE
Correct the HTTP status

### LINKED ISSUE #433: Incorrect use of HTTP status codes
You should be using StatusUnauthorized here https://github.com/ubclaunchpad/inertia/blob/master/daemon/inertiad/auth/permissions.go#L298. There might be some other places where you have a similar issue.

### PR DESCRIPTION
**Pull request by kanozec**
:tickets: **Ticket(s)**: Closes #433 
---

## :construction_worker: Changes

Chang all the bad auth status to http.StatusUnauthorized

## :flashlight: Testing Instructions

Explain how to test your changes, if applicable.

### CODE REVIEW

File: cmd/users.go [hunk 1]
```diff
@@ -99,7 +99,7 @@ from the web app.`,
 		switch resp.StatusCode {
 		case http.StatusOK:
 			fmt.Printf("(Status code %d) User removed.\n", resp.StatusCode)
-		case http.StatusForbidden:
+		case hhttp.StatusUnauthorized:
```
Comment (bobheadxi) [inline cmd/users.go]: typo here! 😄
