### PR TITLE
Brian/#199 extract repo name

### LINKED ISSUE #199: Failing to extract repo names with hyphens
Regexp fails when username/repo includes hyphens.

### PR DESCRIPTION
**Pull request by brian-nguyen**
:tickets: **Ticket(s)**: Closes #199 

---

## :construction_worker: Changes

Modified regular expression to extract `<username/organization>/<repoName>` for cases where the names include periods and dashes.

## :flashlight: Testing Instructions

Expanded TestExtractRepository to verify these cases.

### CODE REVIEW

**Comment by bobheadxi** [comment]
Don't worry about the Travis failures - I don't think it's anything caused by this PR. I'll let them run again and hopefully they'll pass this time 😞

File: deploy.go [hunk 1]
```diff
@@ -260,7 +260,10 @@ for updates to this repository's remote master branch.`,
 			if err != nil {
 				log.Fatal(err)
 			}
-			repoName := common.ExtractRepository(common.GetSSHRemoteURL(origin.Config().URLs[0]))
+			repoName, err := common.ExtractRepository(common.GetSSHRemoteURL(origin.Config().URLs[0]))
+			if err != nil {
+				log.Fatal(err)
```
Comment (bobheadxi) [inline deploy.go]: While the error check is good, I'm a bit iffy on `ExtractRepository` blocking remote setup since it's a purely cosmetic thing (used to generate direct links to repo configuration post-bootstrap).

Maybe we could have some kind of warning instead, and assign `repoName = $YOUR_REPOSITORY` (so that the post-bootstrap output will print something like `"go to https://github.com/$YOUR_REPOSITORY/settings"` )

File: common/util_test.go [hunk 2]
```diff
@@ -115,6 +115,20 @@ func TestFlushRoutine(t *testing.T) {
...
+
+	repoNameWithHyphens, err := ExtractRepository("git@github.com:ubclaunchpad/inertia-deploy-test.git")
+	assert.Nil(t, err)
+	assert.Equal(t, "ubclaunchpad/inertia-deploy-test", repoNameWithHyphens)
+
+	repoNameWithDots, err := ExtractRepository("git@github.com:ubclaunchpad/inertia.deploy.test.git")
+	assert.Nil(t, err)
+	assert.Equal(t, "ubclaunchpad/inertia.deploy.test", repoNameWithDots)
+
+	repoNameWithMixed, err := ExtractRepository("git@github.com:ubclaunchpad/inertia-deploy.test.git")
```
Comment (bobheadxi) [inline common/util_test.go]: 🔥

File: common/util_test.go [hunk 3]
```diff
@@ -131,4 +131,8 @@ func TestExtract(t *testing.T) {
 	repoNameWithMixed, err := ExtractRepository("git@github.com:ubclaunchpad/inertia-deploy.test.git")
 	assert.Nil(t, err)
 	assert.Equal(t, "ubclaunchpad/inertia-deploy.test", repoNameWithMixed)
+
+	repoNameWithErr, err := ExtractRepository("asdfasda")
```
Comment (bobheadxi) [inline common/util_test.go]: 💯 

capture2
