### PR TITLE
Dockerfile ports, containerstop fixes, minor updates

### LINKED ISSUE #351: Dockerfile builds don't expose ports properly

### PR DESCRIPTION
**Pull request by bobheadxi**
:tickets: **Ticket(s)**: Closes #351

---

## :construction_worker: Changes

See commits - biggest change is that ports exposed in Dockerfile images (via the `EXPOSE` directive) is now automatically mapped to host

## :flashlight: Testing Instructions

build any dockerfile project, check that port is accessible

### CODE REVIEW

File: daemon/inertiad/build/builder.go [hunk 1]
```diff
@@ -299,7 +312,7 @@ func (b *Builder) herokuishBuild(d Config, cli *docker.Client,
 	}
 
 	// Start the herokuish container to build project
-	fmt.Fprintln(out, "Building project...")
+	fmt.Fprintf(out, "Building project %s...\n", d.Name)
```
Comment (leesw98) [inline daemon/inertiad/build/builder.go]: Perhaps you'd want to put duplicate strings in a var for consistency

File: daemon/inertiad/build/builder.go [hunk 2]
```diff
@@ -243,16 +247,25 @@ func (b *Builder) dockerBuild(d Config, cli *docker.Client,
...
 	fmt.Fprintf(out, "%s (%s) build has exited\n", imageName, buildResp.OSType)
 
+	// Get image details
+	image, _, err := cli.ImageInspectWithRaw(ctx, imageName)
+	if err != nil {
+		return nil, err
+	}
+	portMap := nat.PortMap{}
+	for p := range image.Config.ExposedPorts {
+		portMap[p] = []nat.PortBinding{{HostIP: "0.0.0.0", HostPort: p.Port()}}
```
Comment (leesw98) [inline daemon/inertiad/build/builder.go]: `{{...}}` wot. Is hash parameters not a thing in Go?

File: daemon/inertiad/containers/containers.go [hunk 3]
```diff
@@ -94,10 +94,13 @@ func StopActiveContainers(docker *docker.Client, out io.Writer) error {
...
 			timeout := 10 * time.Second
-			err := docker.ContainerStop(ctx, container.ID, &timeout)
-			if err != nil {
+			if err := docker.ContainerStop(ctx, container.ID, &timeout); err != nil {
 				return err
 			}
+
+			// Archive container
+			docker.ContainerRename(
+				ctx, container.ID, fmt.Sprintf("%s-%d", container.Names[0], time.Now().Unix()))
```
Comment (leesw98) [inline daemon/inertiad/containers/containers.go]: What's the point of renaming these containers? Wouldn't we pile up on archived containers in this case if ran for long period?

File: daemon/inertiad/build/builder.go (hunk 2 above)
Comment (bobheadxi) [reply daemon/inertiad/build/builder.go]: What do you mean?

The outer `{}` is the array instantiator, the inner `{}` is for an element

File: daemon/inertiad/build/builder.go (hunk 1 above)
Comment (bobheadxi) [reply daemon/inertiad/build/builder.go]: I was considering that, but wasn't sure if it would be within the scope of the PR - though considering theres a bunch of misc changes, might as well

File: daemon/inertiad/containers/containers.go (hunk 3 above)
Comment (bobheadxi) [reply daemon/inertiad/containers/containers.go]: Ran into some issues with duplicate container names in my testing. The reasoning here is twofold:
- unused containers will be removed by our `Prune()` op, which runs at certain points (pre-build, etc)
- archival might be useful for #293

We definitely need a stronger plan for resource management, but I still have some confusions about how the fuck docker itself manages it. It seems like there is a delay in API call -> thing actually happening, as can be seen in the Travis tests periodically failing. Definitely something that needs more research.
