### PR TITLE
ECS VPS provisioning

### LINKED ISSUE #261: `inertia provision ec2 [name]`
Provision ECS instance and set it up for Inertia

### LINKED ISSUE #277: Investigate amazon linux build failures
Bootstrap integration tests failing for `amazon:latest`:

```
=== RUN   TestBootstrapIntegration
Setting up remote "" at 127.0.0.1
>> Step 1/4: Installing docker...
Error: Nothing to do

--- FAIL: TestBootstrapIntegration (4.83s)
	Error Trace:	client_test.go:183
	Error:		Expected nil, but got: &ssh.ExitError{Waitmsg:ssh.Waitmsg{status:1, signal:"", msg:"", lang:""}}
		
	Error Trace:	client_test.go:195
	Error:		Expected nil, but got: &url.Error{Op:"Get", URL:"https://127.0.0.1:4303", Err:(*net.OpError)(0xc420172140)}
```

Example build: https://travis-ci.org/ubclaunchpad/inertia/jobs/397172380

image

### PR DESCRIPTION
**Pull request by bobheadxi**
:tickets: **Ticket(s)**: Closes #261, closes #277

Relates to #280, #278

---

## :construction_worker: Changes

Adds package `provision` and new commands to provide a utility for quickly creating and setting up a VPS instance on AWS:

```bash
inertia provision [command]
inertia provision ec2 [name] [-t --type (instance type)] [--from-env (load credentials from ENV)]
```

The idea is:
1. Provide users with basic options (region, image, instance type)
2. Create key-pair, save to disk
3. Create instance
4. Save instance configuration as `cfg.RemoteVPS`
5. Initialize VPS

That way you can do:

```bash
inertia provision ec2 my_vps
inertia my_vps up
```

Updates:
- https://github.com/ubclaunchpad/inertia/pull/265#issuecomment-400587030 (7327eb2)

## To Do

- [x] Flesh out key saving and Inertia configuration setup
- [x] Make sure this works. My account got banned, so this might be hard for me 😅 

## :flashlight: Testing Instructions

Any help testing this would be appreciated! `go get` and checkout the branch, then:

```
make
inertia --version # should be `latest`
```

Then, inside some random repo (ie https://github.com/ubclaunchpad/inertia-deploy-test):

```
inertia init
inertia provision ec2 my_vps
```

- a new `t2.micro` instance should be started
- Inertia daemon should be online at your instance at 4303

### CODE REVIEW

**Comment by bobheadxi** [comment]
Approaches to test:
- adc22e49f21baf0212f5f94b9addf8c5cc5463ad

File: provision/ec2.go [hunk 1]
```diff
@@ -0,0 +1,296 @@
...
+		Ipv6Ranges: []*ec2.Ipv6Range{{CidrIpv6: aws.String("::/0"), Description: aws.String("Inertia SSH port")}},
+	}, {
+		FromPort:   aws.Int64(daemonPort),
+		ToPort:     aws.Int64(daemonPort),
+		IpProtocol: aws.String("tcp"),
+		IpRanges:   []*ec2.IpRange{{CidrIp: aws.String("0.0.0.0/0"), Description: aws.String("Inertia daemon port")}},
+		Ipv6Ranges: []*ec2.Ipv6Range{{CidrIpv6: aws.String("::/0"), Description: aws.String("Inertia daemon port")}},
+	}}
+
+	// Generate rules for user project
```
Comment (brian-nguyen) [inline provision/ec2.go]: Very convenient 👍
